# -*- coding: utf-8 -*-

"""
googledataapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from googledataapi.api_helper import APIHelper


class APITESTControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(APITESTControllerTests, cls).setUpClass()
        cls.controller = cls.client.api_test
        cls.response_catcher = cls.controller.http_call_back

    # Test case used to compare the values for keys
    def test_case_to_compare_keys(self):
        # Parameters for the API call
        part = 'snippet'
        max_results = '1'
        q = 'gaming'
        key = 'AIzaSyCYWHyYEQOTA5V_o_DHMIdmXd0wiHzB0ns'
        mtype = 'video'

        # Perform the API call through the SDK function
        result = self.controller.google_search_api(part, max_results, q, key, mtype)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)
        
        # Test whether the captured response is as we expected
        self.assertIsNotNone(result)
        expected_body = APIHelper.json_deserialize('{\'kind\':\'youtube#searchListResponse\',\'etag\':\'5Tp37XkY1ea8Kf'
            '3aWJHxvFKbquU\',\'nextPageToken\':\'CAEQAA\',\'regionCode\':\'PK\''
            ',\'pageInfo\':{\'totalResults\':1000000,\'resultsPerPage\':1},\'it'
            'ems\':[{\'kind\':\'youtube#searchResult\',\'etag\':\'a2fDl1VjigYDp'
            '3Nj_XOdyuEtQL4\',\'id\':{\'kind\':\'youtube#video\',\'videoId\':\''
            'vn7Vo8M5Mow\'},\'snippet\':{\'publishedAt\':\'2022-06-09T18:30:47Z'
            '\',\'channelId\':\'UCvO9Xk3bheuxEemvknCj72g\',\'title\':\'10WorstV'
            'ideoGamesTo100%\',\'description\':\'Whencompletionissuffering.Form'
            'oreawesomecontent,checkout:http://whatculture.com/gamingCatchusonF'
            'acebookat:...\',\'thumbnails\':{\'default\':{\'url\':\'https://i.y'
            'timg.com/vi/vn7Vo8M5Mow/default.jpg\',\'width\':120,\'height\':90}'
            ',\'medium\':{\'url\':\'https://i.ytimg.com/vi/vn7Vo8M5Mow/mqdefaul'
            't.jpg\',\'width\':320,\'height\':180},\'high\':{\'url\':\'https://'
            'i.ytimg.com/vi/vn7Vo8M5Mow/hqdefault.jpg\',\'width\':480,\'height'
            '\':360}},\'channelTitle\':\'WhatCultureGaming\',\'liveBroadcastCon'
            'tent\':\'none\',\'publishTime\':\'2022-06-09T18:30:47Z\'}}]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        self.assertTrue(TestHelper.match_body(expected_body, received_body))

